# Generated by Django 5.1.1 on 2024-11-02 16:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeInformation',
            fields=[
                ('employee_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('profile_picture', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('birthdate', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('marital_status', models.CharField(max_length=100)),
                ('nationality', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=1000)),
                ('city', models.CharField(max_length=50)),
                ('province', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=10)),
                ('active_phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('date_hired', models.DateField()),
                ('employment_status', models.CharField(max_length=15)),
                ('sss_number', models.CharField(max_length=20)),
                ('pagibig_number', models.CharField(max_length=20)),
                ('philhealth_number', models.CharField(max_length=20)),
                ('tin_number', models.CharField(max_length=20)),
                ('bank_account_number', models.CharField(max_length=20)),
                ('emergency_contact_name', models.CharField(max_length=50)),
                ('emergency_contact_rs', models.CharField(max_length=50)),
                ('emergency_contact_number', models.CharField(max_length=15)),
                ('role', models.CharField(choices=[('Admin', 'Admin'), ('User', 'User')], default='User', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('account_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user_account', serialize=False, to='hrmanagement.employeeinformation')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=10)),
                ('role', models.CharField(choices=[('Admin', 'Admin'), ('User', 'User')], default='User', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('job_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_title', models.CharField(max_length=50)),
                ('salary_min', models.DecimalField(decimal_places=2, max_digits=10)),
                ('salary_max', models.DecimalField(decimal_places=2, max_digits=10)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='hrmanagement.department')),
            ],
        ),
        migrations.AddField(
            model_name='employeeinformation',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_jobs', to='hrmanagement.job'),
        ),
    ]
