# Generated by Django 5.1.3 on 2024-12-04 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrmanagement', '0002_peerfeedback_selfassessment'),
    ]

    operations = [
        migrations.AddField(
            model_name='sanctionreport',
            name='sanction_report_file',
            field=models.FileField(blank=True, null=True, upload_to='sanction_reports/'),
        ),
        migrations.AlterField(
            model_name='sanctionreport',
            name='sanction_type',
            field=models.CharField(choices=[('Written Warning', 'Written Warning'), ('Verbal Warning', 'Verbal Warning'), ('Suspension', 'Suspension'), ('Performance Improvement Plan (PIP)', 'Performance Improvement Plan (PIP)'), ('Demotion', 'Demotion'), ('Termination', 'Termination'), ('Probation', 'Probation'), ('Loss of Privileges', 'Loss of Privileges'), ('Training or Re-Training', 'Training or Re-Training'), ('Demotion in Pay or Benefits', 'Demotion in Pay or Benefits'), ('Suspension of Certain Rights or Benefits', 'Suspension of Certain Rights or Benefits')], max_length=255),
        ),
    ]
