# Generated by Django 5.1.3 on 2024-11-07 11:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrmanagement', '0003_leavetype_adminpayroll_attendancerecord_jobopening_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('training_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('training_name', models.CharField(max_length=500)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainings', to='hrmanagement.employeeinformation')),
            ],
        ),
    ]
