# Generated by Django 5.1.2 on 2024-11-10 18:12

import hrmanagement.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrmanagement', '0003_leavetype_adminpayroll_attendancerecord_jobopening_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='applicant_id',
            field=models.CharField(default=hrmanagement.models.generate_custom_applicant_id, editable=False, max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='employeeinformation',
            name='profile_picture',
            field=models.ImageField(upload_to=hrmanagement.models.EmployeeInformation.upload_profile_picture),
        ),
    ]
