# Generated by Django 5.1.2 on 2024-11-18 17:26

import django.db.models.deletion
import hrmanagement.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrmanagement', '0004_alter_applicant_applicant_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='resume',
            field=models.FileField(upload_to=hrmanagement.models.upload_resume),
        ),
        migrations.CreateModel(
            name='PerformanceReport',
            fields=[
                ('report_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('date_created', models.DateField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_reports', to='hrmanagement.employeeinformation')),
            ],
        ),
        migrations.CreateModel(
            name='PerformanceReview',
            fields=[
                ('review_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('review_comments', models.TextField()),
                ('review_date', models.DateField(auto_now_add=True)),
                ('overall_rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('performance_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_reviews', to='hrmanagement.employeeinformation')),
                ('reviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews_given', to='hrmanagement.employeeinformation')),
            ],
        ),
        migrations.CreateModel(
            name='SanctionReport',
            fields=[
                ('sanction_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sanction_reason', models.CharField(max_length=255)),
                ('sanction_details', models.TextField()),
                ('sanction_type', models.CharField(max_length=255)),
                ('sanction_date', models.DateField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Resolved', 'Resolved')], max_length=50)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sanction_reports', to='hrmanagement.employeeinformation')),
            ],
        ),
    ]
