# Generated by Django 5.1.3 on 2024-11-07 12:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrmanagement', '0005_performancereport'),
    ]

    operations = [
        migrations.CreateModel(
            name='SanctionReport',
            fields=[
                ('sanction_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sanction_reason', models.CharField(max_length=255)),
                ('sanction_details', models.TextField()),
                ('sanction_type', models.CharField(max_length=255)),
                ('sanction_date', models.DateField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Resolved', 'Resolved')], max_length=50)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sanction_reports', to='hrmanagement.employeeinformation')),
            ],
        ),
    ]
