# Generated by Django 5.1.2 on 2024-11-19 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrmanagement', '0006_rename_adminpayroll_employeepayroll_trainings'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='dateAccountAdded',
            field=models.DateField(auto_now=True),
        ),
    ]
