# Generated by Django 5.1.2 on 2024-11-19 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrmanagement', '0007_useraccount_dateaccountadded'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='dateAccountAdded',
            new_name='date_account_added',
        ),
    ]
