# Generated by Django 5.1.3 on 2024-11-07 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrmanagement', '0007_performancereview'),
    ]

    operations = [
        migrations.AddField(
            model_name='performancereview',
            name='performance_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
