# Generated by Django 5.1.2 on 2024-11-24 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrmanagement', '0008_rename_dateaccountadded_useraccount_date_account_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='password',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
