# Generated by Django 5.1.2 on 2024-11-24 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrmanagement', '0009_alter_useraccount_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='username',
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
