# Generated by Django 5.1.2 on 2024-11-24 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrmanagement', '0010_alter_useraccount_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
