# Generated by Django 5.1.3 on 2024-11-27 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrmanagement', '0012_alter_sanctionreport_sanction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='sanctionreport',
            name='sanction_report_file',
            field=models.FileField(blank=True, null=True, upload_to='sanction_reports/'),
        ),
    ]
