# Generated by Django 5.1.1 on 2024-12-01 12:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrmanagement', '0013_sanctionreport_sanction_report_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeerFeedback',
            fields=[
                ('feedback_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('peer_name', models.CharField(max_length=255)),
                ('performance', models.CharField(choices=[('exceeds-expectations', 'Exceeds expectations'), ('meets-expectations', 'Meets expectations'), ('needs-improvement', 'Needs improvement'), ('unsatisfactory', 'Unsatisfactory')], max_length=255)),
                ('cooperation', models.CharField(choices=[('highly-cooperative', 'Highly cooperative'), ('generally-cooperative', 'Generally cooperative'), ('needs-improvement', 'Needs improvement in collaboration'), ('rarely-cooperative', 'Rarely cooperative')], max_length=255)),
                ('attitude', models.CharField(choices=[('always-positive', 'Always positive and motivated'), ('mostly-positive', 'Mostly positive'), ('neutral', 'Neutral'), ('often-negative', 'Often negative or demotivated')], max_length=255)),
                ('problem_solving', models.CharField(choices=[('excellent', 'Excellent problem-solving skills'), ('adequate', 'Adequate problem-solving skills'), ('needs-guidance', 'Needs guidance frequently'), ('struggles', 'Struggles significantly with problem-solving')], max_length=255)),
                ('leadership', models.CharField(choices=[('yes', 'Yes, absolutely'), ('maybe', 'Maybe, with further development'), ('not-at-this-time', 'Not at this time'), ('no', 'No')], max_length=255)),
                ('feedback_date', models.DateField(auto_now_add=True)),
                ('feedback_comments', models.TextField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peer_feedbacks', to='hrmanagement.employeeinformation')),
            ],
        ),
    ]
