# Generated by Django 5.1.1 on 2024-12-01 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrmanagement', '0014_peerfeedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peerfeedback',
            name='peer_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_feedbacks', to='hrmanagement.employeeinformation'),
        ),
    ]
