# Generated by Django 5.1.1 on 2024-12-01 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrmanagement', '0015_alter_peerfeedback_peer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peerfeedback',
            name='peer_name',
            field=models.CharField(max_length=255),
        ),
    ]
