# Generated by Django 5.1.1 on 2024-12-02 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrmanagement', '0017_alter_peerfeedback_peer_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation_date', models.DateField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='hrmanagement.employeeinformation')),
                ('evaluator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluations_given', to='hrmanagement.employeeinformation')),
                ('question_1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_1_answers', to='hrmanagement.evaluationquestion')),
                ('question_2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_2_answers', to='hrmanagement.evaluationquestion')),
                ('question_3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_3_answers', to='hrmanagement.evaluationquestion')),
                ('question_4', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_4_answers', to='hrmanagement.evaluationquestion')),
                ('question_5', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_5_answers', to='hrmanagement.evaluationquestion')),
            ],
        ),
        migrations.DeleteModel(
            name='PeerFeedback',
        ),
    ]
