# Generated by Django 5.1.3 on 2024-12-02 11:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrmanagement', '0018_evaluationquestion_employeeevaluation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeerEvaluationQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackQuestionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrmanagement.peerevaluationquestion')),
            ],
        ),
        migrations.CreateModel(
            name='PeerFeedback',
            fields=[
                ('feedback_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_given', to='hrmanagement.employeeinformation')),
                ('questions', models.ManyToManyField(through='hrmanagement.FeedbackQuestionAnswer', to='hrmanagement.peerevaluationquestion')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_received', to='hrmanagement.employeeinformation')),
            ],
            options={
                'unique_together': {('from_user', 'to_user', 'created_at')},
            },
        ),
        migrations.AddField(
            model_name='feedbackquestionanswer',
            name='feedback',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrmanagement.peerfeedback'),
        ),
        migrations.DeleteModel(
            name='EmployeeEvaluation',
        ),
        migrations.DeleteModel(
            name='EvaluationQuestion',
        ),
    ]
