# Generated by Django 5.1.3 on 2024-12-02 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrmanagement', '0019_peerevaluationquestion_feedbackquestionanswer_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='peerfeedback',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='peerfeedback',
            name='question_1',
            field=models.IntegerField(blank=True, choices=[(1, 'Poor'), (2, 'Fair'), (3, 'Good'), (4, 'Excellent')], null=True),
        ),
        migrations.AddField(
            model_name='peerfeedback',
            name='question_2',
            field=models.IntegerField(blank=True, choices=[(1, 'Poor'), (2, 'Fair'), (3, 'Good'), (4, 'Excellent')], null=True),
        ),
        migrations.AddField(
            model_name='peerfeedback',
            name='question_3',
            field=models.IntegerField(blank=True, choices=[(1, 'Poor'), (2, 'Fair'), (3, 'Good'), (4, 'Excellent')], null=True),
        ),
        migrations.AddField(
            model_name='peerfeedback',
            name='question_4',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='peerfeedback',
            name='question_5',
            field=models.IntegerField(blank=True, choices=[(1, 'Poor'), (2, 'Fair'), (3, 'Good'), (4, 'Excellent')], null=True),
        ),
        migrations.AddField(
            model_name='peerfeedback',
            name='question_6',
            field=models.IntegerField(blank=True, choices=[(1, 'Poor'), (2, 'Fair'), (3, 'Good'), (4, 'Excellent')], null=True),
        ),
        migrations.RemoveField(
            model_name='peerfeedback',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='peerfeedback',
            name='questions',
        ),
        migrations.RemoveField(
            model_name='peerfeedback',
            name='rating',
        ),
        migrations.DeleteModel(
            name='FeedbackQuestionAnswer',
        ),
        migrations.DeleteModel(
            name='PeerEvaluationQuestion',
        ),
    ]
