# Generated by Django 5.1.3 on 2024-12-03 04:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrmanagement', '0020_alter_peerfeedback_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelfAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('self_assessment_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('performance_rating', models.IntegerField(choices=[(1, 'Poor'), (2, 'Fair'), (3, 'Good'), (4, 'Excellent')])),
                ('skill_development', models.IntegerField(choices=[(1, 'Poor'), (2, 'Fair'), (3, 'Good'), (4, 'Excellent')])),
                ('teamwork', models.IntegerField(choices=[(1, 'Needs Improvement'), (2, 'Satisfactory'), (3, 'Effective'), (4, 'Highly Effective')])),
                ('communication_skills', models.IntegerField(choices=[(1, 'Poor'), (2, 'Fair'), (3, 'Good'), (4, 'Excellent')])),
                ('company_culture', models.IntegerField(choices=[(1, 'Poorly Aligned'), (2, 'Somewhat Aligned'), (3, 'Well Aligned'), (4, 'Fully Aligned')])),
                ('work_life_balance', models.IntegerField(choices=[(1, 'Poor'), (2, 'Fair'), (3, 'Good'), (4, 'Excellent')])),
                ('suggestions_for_improvement', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='self_assessments', to='hrmanagement.employeeinformation')),
            ],
        ),
    ]
