# Generated by Django 5.1.3 on 2024-11-29 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hraccount', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='plain_password',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
