# Generated by Django 5.1.3 on 2024-11-29 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hraccount', '0002_useraccount_plain_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='plain_password',
        ),
    ]
