# Generated by Django 5.1.3 on 2024-11-29 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hraccount', '0003_remove_useraccount_plain_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='plain_password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
