# Generated by Django 5.1.3 on 2024-12-03 15:35

import django.db.models.deletion
import hraccount.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hraccount', '0005_remove_useraccount_plain_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeinformation',
            name='role',
        ),
        migrations.RemoveField(
            model_name='job',
            name='salary_max',
        ),
        migrations.RemoveField(
            model_name='job',
            name='salary_min',
        ),
        migrations.AddField(
            model_name='job',
            name='job_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='requirements',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='salary_range',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('OPEN', 'open'), ('CLOSED', 'closed'), ('FILLED', 'filled')], default=hraccount.models.JobStatus['OPEN'], max_length=20),
        ),
        migrations.AlterField(
            model_name='employeeinformation',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=hraccount.models.EmployeeInformation.upload_profile_picture),
        ),
        migrations.AlterField(
            model_name='job',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hraccount.department'),
        ),
    ]
